#!/bin/sh

if [ -e /tmp/mini-httpd.pid ]; then
  PID=$(</tmp/mini-httpd.pid)
  kill -9 $PID
  rm -fr /tmp/mini-httpd.pid
fi

eval "(python -m SimpleHTTPServer &> httpd.log) &"
PID=$!
echo $PID > /tmp/mini-httpd.pid
